#!/bin/sh

# shell script to prepend i3status with more stuff
i3status | while :; do
  read -r line
  mem=$(awk '/MemTotal/ {memtotal=$2}; /MemAvailable/ {memavail=$2}; END { printf("%.0f", memavail / memtotal * 100) }' /proc/meminfo)
  echo "$mem% | ${line#,\[}" || exit 1
done
