#!/bin/bash

# sakura --hold -e 'tmux'

if [[ -z "$TMUX" ]] ;then
	# get the id of a deattached session
	ID="`tmux ls | grep attached | grep notes | cut -d: -f1`"
	# if not available create a new one
	if [[ -z "$ID" ]] ;then
		sakura --hold -e 'tmuxinator notes'
		#tmux new-session
	else
		# if available attach to it
		sakura -h -x 'tmux attach-session -t "$ID"'
	fi
fi
