#!/bin/bash
setxkbmap us && 	\
# xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
# setxkbmap -layout us -variant altgr-intl -option nodeadkeys
setxkbmap -option caps:swapescape && \

notify-send 'US Keyboard' --icon=dialog-information
