#!/bin/bash

if [[ -z "$TMUX" ]] ;then
	# get the id of a deattached session
	ID="`tmux ls | grep attached | grep main | cut -d: -f1`"
	# if not available create a new one
	if [[ -z "$ID" ]] ;then
		xfce4-terminal --title='Terminal - localhost' -e 'tmuxinator main'
		#tmux new-session
	else
		# if available attach to it
		xfce4-terminal --title='Terminal - localhost' -x 'tmux attach-session -t "$ID"'
	fi
fi
